### ISSUE TITLE
Split DevIL repositories

### ISSUE THREAD

**Issue by AMDmi3** [DentonW/DevIL#10]
Apart from DevIL source code, DevIL repository currently contains docs, utils and test images. These should be split into separate repositories due to many reasons, such as convenience (users who only need DevIL sources won't need to download 200MB of test images) and legal reasons (as you state, test images may contain copyrighted work, so it should not be distributed with DevIL). Split may be done easily with git filter branch, see `git help filter-branch`, EXAMPLES section, example for --subdirectory-filter.

**Comment by abma** [comment]
was done some time ago: the repository has currently ~20MB.
