### ISSUE TITLE
Link errors with inline functions

### ISSUE THREAD

**Issue by bcampbell** [DentonW/DevIL#20]
(Not really a bug report yet - mainly a place to dump my thoughts!)

I hadn't realised just how fragmented support was for inline functions across different compilers!
I'm doing some CMake work and having a lot of trouble with inline functions.

Usually problems manifest as symbols being multiply defined (eg function bodies in header files being instantiated every time they're included) or symbols missing (eg inlining working fine, but the library still referencing a function which was never generated as a stand-alone thing).

As I see it, DevIL needs to support three distinct sets of inline rules:
1. C99  (eg clang on OSX, GCC with -std=c99)
2. GNU C (legacy GCC)
3. C++ (most specifically Visual C/C++ which compiles C as C++?)

(Details of the C99 and GNU rules here:
http://www.greenend.org.uk/rjk/tech/inline.html)

That web page has some strategies for dealing with this issue, and DevIL definitely applies it in various places. But it'd be nice to be a bit more explicit on how inlines are handled.

Anyway, I'll be tinkering with various approaches, and will add notes here as I go.

**Comment by bcampbell** [comment]
__GNUC_STDC_INLINE__ looks like a good way to detect C99-style inline handling on clang and gcc. Both compilers support it.
(clang compiles as C99 by default and gcc does when compiling with `-std=c99` or higher).

**Comment by bcampbell** [comment]
OK, I've found a simple approach that works for me:
I converted all the `inline` functions into `static inline`.

Code on https://github.com/bcampbell/DevIL/tree/static-inlines

It cuts away a lot of tricky preprocessor juggling, and seems very simple and compatible (C++, C99, GNU89 etc...)

It compiles fine for me now on Linux (GCC, in both C99 and GNU89 modes), and on Mac (clang).
If anyone tries it on MSVC, let me know how you get on!

I've added a little check to use `static __inline` if compiling C with MSVC, but I've not tested it. But MSVC compiles C as C++ by default anyway, so it's a minor point I think.

**Comment by lzubiaur** [comment]
@bcampbell thank your work! I tried on Mac (will try on MSVC soon) and it compiles fine but I get  warnings about illegal character encoding from the localized error messages (ilu_err-*.h). Do you know how I can fix this?

**Comment by bcampbell** [comment]
@lzubiaur: sorry, I've not looked much at ILU yet, but I hope to do so soon. I'm going to close this issue, but feel free to open a new one to handle the encoding problem if you're still interested!

**Comment by bcampbell** [comment]
static inline issue is fixed by: 7decfcc089c363d43cf4829544a62a493740ac44
