### ISSUE TITLE
release packages

### ISSUE THREAD

**Issue by Agadoul** [DentonW/DevIL#44]
Hi,
Do you expect to release any release package of the source ?
I am writting a vcpkg port for devIL (https://github.com/Microsoft/vcpkg) and it is better with a downloadable package.
best regards,
Axel.

**Comment by DentonW** [comment]
I've been working on some changes and incorporating ones that people have submitted since the last release years ago. I will try to remember to let you know when I do.

**Comment by Agadoul** [comment]
Thanks. For now, i have started the vcpkg script based on latest version of the master branch but this is not standard.

**Comment by Agadoul** [comment]
Thanks for 1.8.0 release.
