### ISSUE TITLE
compilation Error :

### ISSUE THREAD

**Issue by Aravind1136** [DentonW/DevIL#48]
Hi,
 I was trying to cross- compile devIL for a intel x64bit linux hardware , but i get a compilation error while doing a make,i followed the steps in ReadMe.cmake file .does anybody came across these problems,kindly comment

/home/zjlkk8/libILU/DevIL-master/DevIL/src-IL/src/il_jpeg.cpp: In function 'boolean fill_input_buffer(j_decompress_ptr)':
/home/zjlkk8/libILU/DevIL-master/DevIL/src-IL/../include/IL/il.h:118:20: **error: invalid conversion from 'int' to 'boolean' [-fpermissive]**
 **#define IL_FALSE   0**
                    ^
/home/zjlkk8/libILU/DevIL-master/DevIL/src-IL/src/il_jpeg.cpp:248:10: note: in expansion of macro 'IL_FALSE'
   **return IL_FALSE;**

**Comment by DentonW** [comment]
This is the first time I've seen something like this. What distribution are you using? It seems that the compiler is being stricter about boolean conversions than Ubuntu 16.04. Can you try changing line 248 of il_jpeg.cpp in src-IL/src to return (boolean)IL_FALSE; ?

**Comment by ryandesign** [comment]
I also see such an error trying to compile DevIL 1.8.0 on macOS 10.12 Sierra. (I'm the maintainer of DevIL in MacPorts, trying to update our port.) Here are the first few errors:

```
/opt/local/var/macports/build/_Users_rschmidt_macports_macports-ports_devel_libdevil/libdevil/work/DevIL/DevIL/src-IL/src/il_jpeg.cpp:248:10: error: cannot initialize return object of type 'boolean' with an rvalue of type 'int'
                return IL_FALSE;
                       ^~~~~~~~
/opt/local/var/macports/build/_Users_rschmidt_macports_macports-ports_devel_libdevil/libdevil/work/DevIL/DevIL/src-IL/../include/IL/il.h:118:20: note: expanded from macro 'IL_FALSE'
#define IL_FALSE                        0
                                        ^
/opt/local/var/macports/build/_Users_rschmidt_macports_macports-ports_devel_libdevil/libdevil/work/DevIL/DevIL/src-IL/src/il_jpeg.cpp:256:21: error: assigning to 'boolean' from incompatible type 'int'
        src->start_of_file = IL_FALSE;
                           ^ ~~~~~~~~
/opt/local/var/macports/build/_Users_rschmidt_macports_macports-ports_devel_libdevil/libdevil/work/DevIL/DevIL/src-IL/src/il_jpeg.cpp:258:9: error: cannot initialize return object of type 'boolean' with an rvalue of type 'int'
        return IL_TRUE;
               ^~~~~~~
/opt/local/var/macports/build/_Users_rschmidt_macports_macports-ports_devel_libdevil/libdevil/work/DevIL/DevIL/src-IL/../include/IL/il.h:119:20: note: expanded from macro 'IL_TRUE'
#define IL_TRUE                         1
                                        ^
```

Note that this is with jpeg 9b. jpeg 8 and later have changed how Booleans are handled.

**Comment by ryandesign** [comment]
> Note that this is with jpeg 9b. jpeg 8 and later have changed how Booleans are handled.

https://trac.macports.org/ticket/42735#comment:8

**Comment by DentonW** [comment]
Could you try the latest commit to see if I missed any typecasts?

**Comment by abma** [comment]
for me it worked
